### ISSUE TITLE
No images get created anymore

### ISSUE THREAD

**Issue by selfthinker** [splitbrain/dokuwiki-plugin-ditaa#14]
Since the last update no images get created for me anymore. Version 2014-01-02 works fine for me but with the latest version I get the following error:

> PHP Warning:  Invalid argument supplied for foreach() in /var/www/wiki/lib/plugins/ditaa/syntax.php on line 105

**Comment by einhirn** [comment]
Problem is this commit https://github.com/splitbrain/dokuwiki-plugin-ditaa/commit/38c9279020ea3c3abc0a18e7d236f87252b3f01b
It removes line 112 "md5" from the fields that are passed on to the cache file name creation. See the line comment there.
